
CREATE TABLE RodzajeRealizacji (
    id_rodzaju INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) CONSTRAINT pk_id_rodzaju PRIMARY KEY,
    typ CHARACTER VARYING(50) NOT NULL,
    metoda CHAR(1) NOT NULL CONSTRAINT chk_metoda CHECK (metoda IN ('W','B')),
    nazwa_kuriera CHARACTER VARYING(45),
    numer_listu_przewozowego CHARACTER VARYING(50) UNIQUE,
    CONSTRAINT sprawdz_wysylka CHECK (
        (metoda = 'W' AND nazwa_kuriera IS NOT NULL AND numer_listu_przewozowego IS NOT NULL) OR
        (metoda = 'B' AND nazwa_kuriera IS NULL AND numer_listu_przewozowego IS NULL)
    )
);


CREATE TABLE Priorytety (
    waga_naprawy CHARACTER VARYING(15) CONSTRAINT pk_waga_naprawy PRIMARY KEY CONSTRAINT check_priorytet CHECK (waga_naprawy IN ('Krytyczny','Wysoki','Średni', 'Niski')),
    czas_na_wykonanie INTERVAL DAY TO SECOND NOT NULL
);


CREATE TABLE Franczyzobiorcy (
    pesel CHAR(11) CONSTRAINT pk_pesel_franczyzobiorcy PRIMARY KEY,
    imię CHARACTER VARYING(20) NOT NULL,
    nazwisko CHARACTER VARYING(30) NOT NULL,
    telefon CHARACTER VARYING(9) NOT NULL UNIQUE,
    email CHARACTER VARYING(50) UNIQUE,
    CONSTRAINT chk_email_franczyzobiorcy CHECK (email LIKE '%@%.%')
);


CREATE TABLE Sklepy (
    id_sklepu INTEGER CONSTRAINT pk_id_sklepu PRIMARY KEY,
    miasto CHARACTER VARYING(40) NOT NULL,
    kod_pocztowy CHAR(6) NOT NULL,
    adres CHARACTER VARYING(50) NOT NULL,
    pesel_franczyzobiorcy CHAR(11) NOT NULL,
    CONSTRAINT fk_franczyzobiorcy FOREIGN KEY(pesel_franczyzobiorcy) REFERENCES Franczyzobiorcy(pesel),
    CONSTRAINT chk_miasto_ulica UNIQUE (miasto, adres),
    CONSTRAINT chk_kod_pocztowy CHECK (kod_pocztowy LIKE '__-___')
);


CREATE TABLE Serwisanci (
    pesel CHAR(11) CONSTRAINT pk_pesel_serwisanta PRIMARY KEY,
    imię CHARACTER VARYING(10) NOT NULL,
    nazwisko CHARACTER VARYING(20) NOT NULL,
    telefon CHARACTER VARYING(9) NOT NULL UNIQUE,
    email CHARACTER VARYING(50) UNIQUE,
    CONSTRAINT chk_email_serwisanta CHECK (email LIKE '%@%.%')
);


CREATE TABLE Sprzęt_IT (
    nr_seryjny CHAR(30) PRIMARY KEY,
    nazwa_urządzenia CHARACTER VARYING(20) NOT NULL CONSTRAINT chk_urzadzenie CHECK (nazwa_urządzenia IN ('Komputer', 'Monitor', 'Drukarka','Skaner')),
    dysk CHARACTER VARYING(30),
    przeznaczenie CHARACTER VARYING(50),
    ilość_ramu INTEGER,
    rozdzielczość CHARACTER VARYING(20),
    czy_dotyk CHAR(1) CONSTRAINT chk_dotyk CHECK (czy_dotyk IN ('T', 'N')),
    rodzaj CHARACTER VARYING(10) CONSTRAINT chk_rodzaj CHECK (rodzaj IN ('fiskalna', 'zapleczowa')),
    id_sklepu INTEGER NOT NULL,
    CONSTRAINT chk_komputer CHECK (
        (nazwa_urządzenia = 'Komputer' AND dysk IS NOT NULL AND przeznaczenie IS NOT NULL AND ilość_ramu IS NOT NULL) OR
        (nazwa_urządzenia <> 'Komputer' AND dysk IS NULL AND przeznaczenie IS NULL AND ilość_ramu IS NULL)
    ),
    CONSTRAINT chk_monitor CHECK (
        (nazwa_urządzenia = 'Monitor' AND rozdzielczość IS NOT NULL AND czy_dotyk IS NOT NULL) OR
        (nazwa_urządzenia <> 'Monitor' AND rozdzielczość IS NULL AND czy_dotyk IS NULL)
    ),
    CONSTRAINT chk_drukarka CHECK (
        (nazwa_urządzenia = 'Drukarka' AND rodzaj IS NOT NULL) OR
        (nazwa_urządzenia <> 'Drukarka' AND rodzaj IS NULL)
    ),
    CONSTRAINT chk_ram_komputer CHECK (
    (nazwa_urządzenia = 'Komputer' AND ilość_ramu > 0) OR
    (nazwa_urządzenia <> 'Komputer' AND ilość_ramu IS NULL)
    ),
    CONSTRAINT fk_id_sklepu_1 FOREIGN KEY (id_sklepu) REFERENCES Sklepy(id_sklepu) ON DELETE CASCADE
);


CREATE TABLE Zgłoszenia (
    id_zgłoszenia INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1)  CONSTRAINT pk_id_zgłoszenia PRIMARY KEY,
    data_zgŁoszenia DATE DEFAULT SYSDATE NOT NULL,
    kategoria CHARACTER VARYING(100) NOT NULL,
    opis_zgłoszenia CHARACTER VARYING(500),
    id_sklepu INTEGER NOT NULL,
    id_rodzaju INTEGER NOT NULL,
    priorytet CHARACTER VARYING(15) NOT NULL,
    id_sprzętu CHAR(30) NOT NULL,
    CONSTRAINT fk_id_sklepu_2 FOREIGN KEY(id_sklepu) REFERENCES Sklepy(id_sklepu) ON DELETE CASCADE,
    CONSTRAINT fk_id_rodzaju FOREIGN KEY(id_rodzaju) REFERENCES RodzajeRealizacji(id_rodzaju),
    CONSTRAINT fk_id_sprzętu FOREIGN KEY(id_sprzętu) REFERENCES Sprzęt_IT(nr_seryjny),
    CONSTRAINT fk_priotytet FOREIGN KEY(priorytet) REFERENCES Priorytety(waga_naprawy)
);


CREATE TABLE Historie_zgłoszenia (
    status CHARACTER VARYING(30) DEFAULT 'Do zrobienia' NOT NULL CONSTRAINT chk_status CHECK (status IN ('Do zrobienia', 'Przypisane', 'W trakcie realizacji', 'Zakończone', 'Anulowane')),
    data_aktualizacji DATE DEFAULT SYSDATE NOT NULL,
    id_zgłoszenia INTEGER NOT NULL,
    pesel_serwisanta CHAR(11) DEFAULT NULL,
    CONSTRAINT chk_pesel_serwisanta_status CHECK (
    (status = 'Anulowane' AND pesel_serwisanta IS NULL) OR
    (status <> 'Anulowane')
    ),
    CONSTRAINT fk_id_zgłoszenia FOREIGN KEY (id_zgłoszenia) REFERENCES Zgłoszenia(id_zgłoszenia) ON DELETE CASCADE,
    CONSTRAINT fk_pesel_serwisanta FOREIGN KEY (pesel_serwisanta) REFERENCES Serwisanci(pesel) ON DELETE SET NULL,
    CONSTRAINT pk_historii_zgłoszenia PRIMARY KEY (status, data_aktualizacji, id_zgłoszenia),
    CONSTRAINT chk_unikalny_status UNIQUE (id_zgłoszenia, status)
);
